// Regenerate content/decisions.md from the ADRs in phd-lab.
//
// Why a generator and a committed file rather than a build-time read: GitHub Actions checks out
// this repo alone and phd-lab is a separate private repo. A build that read phd-lab directly
// would find seventeen decisions here and zero in CI, and it would exit 0 while the deploy
// dropped all of them. So the source of truth is read here, on a machine that can see it, and
// the result is committed.
//
// The summaries are AUTHORED and are never generated. This script preserves every summary
// already in content/decisions.md, keyed by id, and adds new ADRs with an empty summary so they
// are visible and blocking rather than silently absent. A generated restatement of a 1,600-word
// decision is noise wearing a summary's shape.
//
// Run: node scripts/decisions.mjs
// See phd-lab#98.
import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";

const LAB = process.env.PHD_LAB ?? path.resolve("../../phd-lab");
const OUT = "content/decisions.md";
const PAPERS = { "underwater-hydro-fidelity": "paper 1", "compositional-skill-reuse": "paper 2" };

const read = (f) => fs.readFileSync(f, "utf8").replace(/\r\n/g, "\n");

// Every date comes from the ADR's own "**Status:** locked <date>" line, never from the file's
// mtime or its last commit. Those record when the file was touched, not when the decision was
// made: seven of these files were last committed on one day in August and six of them record
// decisions taken in July. Pairing a file's date with a decision is a broken join.
function statusDate(body) {
  const line = body.split("\n").find((l) => /^\*\*Status:\*\*/.test(l));
  if (!line) return null;
  const m = line.match(/(\d{4}-\d{2}-\d{2})/);
  return m ? m[1] : null;
}

function scan() {
  const found = [];
  for (const [dir, label] of Object.entries(PAPERS)) {
    const d = path.join(LAB, "papers", dir, "decisions");
    if (!fs.existsSync(d)) throw new Error(`decisions: ${d} does not exist. Set PHD_LAB or run from code/phd.`);
    for (const f of fs.readdirSync(d).filter((x) => /^\d{4}-.*\.md$/.test(x)).sort()) {
      const body = read(path.join(d, f));
      const num = f.slice(0, 4);
      const title = (body.split("\n").find((l) => l.startsWith("# ")) ?? "").replace(/^#\s*/, "").trim();
      const date = statusDate(body);
      if (!date) throw new Error(`decisions: ${dir}/${f} has no "**Status:** <date>" line to date it by`);
      found.push({ id: `${dir}/${num}`, paper: label, n: num, date, title });
    }
  }
  return found.sort((a, b) => b.date.localeCompare(a.date) || b.id.localeCompare(a.id));
}

const prior = fs.existsSync(OUT) ? (matter(read(OUT)).data.decisions ?? []) : [];
const summaries = new Map(prior.map((d) => [d.id, d.summary]));

const rows = scan().map((d) => ({ ...d, summary: summaries.get(d.id) ?? "" }));
const missing = rows.filter((r) => !r.summary);

const y = (s) => `"${String(s).replace(/"/g, '\\"')}"`;
const stamp = new Date().toLocaleDateString("sv-SE", { timeZone: "America/New_York" });
const out = `---
# GENERATED by scripts/decisions.mjs from phd-lab/papers/*/decisions/. Do not hand-edit the ids,
# dates or titles: re-run the generator instead. The summaries ARE hand-written and are preserved
# across runs, keyed by id. A decision with an empty summary fails the site build rather than
# warning, because a warning in a build that exits 0 is how a gap ships.
#
# Dates are each ADR's own "**Status:** locked" date, not the file's commit date.
generated: ${stamp}
source_count: ${rows.length}
decisions:
${rows.map((d) => `  - id: ${y(d.id)}\n    paper: ${y(d.paper)}\n    date: ${d.date}\n    title: ${y(d.title)}\n    summary: ${y(d.summary)}`).join("\n")}
---
`;
fs.writeFileSync(OUT, out);
console.log(`decisions: wrote ${rows.length} records to ${OUT}, generated ${stamp}`);
if (missing.length) {
  console.error(`decisions: ${missing.length} record(s) have no summary and will FAIL the site build:`);
  for (const m of missing) console.error(`  ${m.id}  ${m.date}  ${m.title.slice(0, 70)}`);
  process.exit(1);
}
